---
title: "Chung-2017 metadata"
output:
  pdf_document: default
  html_notebook:
    code_folding: hide
    depth: 3
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
  word_document: default
---

```{r}
globus_metadata <-  readRDS("/mnt/nmorais-nfs/marta/pC_myeinfobank/metadata/globus/processed/GSE75688_chung_fluidigm.rds")
```

```{r}
globus_metadata
```

```{r}
colnames(globus_metadata@meta.data)
```

```{r}
table(globus_metadata$patient)
table(globus_metadata$batch)
table(globus_metadata$condition)
table(globus_metadata$sex)
table(globus_metadata$tissue)
```

```{r}
colnames(globus_metadata)[1:5]
```

```{r}
metadata <- data.frame(Cell_ID = colnames(globus_metadata),
                       Patient = globus_metadata$patient,
                       Subtype = globus_metadata$condition)
```

```{r}
rownames(metadata) <- NULL
```

```{r}
table(metadata$Subtype)
metadata$Subtype <- gsub("ER-HER2\\+", "HER2+/ER+", metadata$Subtype)
table(metadata$Subtype)
```

```{r}
metadata$Sample <- gsub("GSE75688_", "", metadata$Patient)
metadata$Patient <- gsub("GSE75688_", "", metadata$Patient)
metadata$Patient <- gsub("BC09_Re", "BC09", metadata$Patient)
metadata$Patient <- gsub("BC03LN", "BC03", metadata$Patient)
metadata$Patient <- gsub("BC07LN", "BC07", metadata$Patient)
```

```{r}
table(metadata$Patient, metadata$Sample)
```

```{r}
metadata$Gender <- "Female"
metadata$Cancer_Type <- "IDC"
```

```{r}
metadata$Tissue <- "Tumour"
metadata$Tissue[metadata$Sample == "BC07LN"] <- "Lymph-node"
metadata$Tissue[metadata$Sample == "BC03LN"] <- "Lymph-node"
```

```{r}
table(metadata$Tissue, metadata$Sample)
```

```{r}
metadata$Treatment_Status <- "Naive"
metadata$Treatment_Status[metadata$Patient == "BC05"] <- "Treated"
metadata$Treatment_Type <- "None"
metadata$Treatment_Type[metadata$Patient == "BC05"] <- "Chemotherapy, Herceptin"
```

```{r}
table(metadata$Patient, metadata$Treatment_Type)
table(metadata$Treatment_Status, metadata$Treatment_Type)
```
```{r}
metadata$Dissociation <- "Mechanical,Enzymatic"
metadata$Technology <- "Fluidigm"
metadata$Protocol <- "SMARTer Ultra Low RNA Kit"
metadata$Sample_Type <- "Fresh"
metadata$CellorNucleus <- "Cell"
metadata$Sequencing_Machine <- "Illumina_HiSeq_2500"
metadata$Preprocessing <- "Kallisto"
metadata$Reference_Genome <- "hg38"
```

```{r}
table(metadata$Patient, metadata$Subtype)
```

```{r}
metadata$Age <- metadata$Patient
metadata$Age[metadata$Patient == "BC01"] <- 66
metadata$Age[metadata$Patient == "BC02"] <- 72
metadata$Age[metadata$Patient == "BC03"] <- 72
metadata$Age[metadata$Patient == "BC04"] <- 67
metadata$Age[metadata$Patient == "BC05"] <- 46
metadata$Age[metadata$Patient == "BC06"] <- 67
metadata$Age[metadata$Patient == "BC07"] <- 71
metadata$Age[metadata$Patient == "BC08"] <- 67
metadata$Age[metadata$Patient == "BC09"] <- 53
metadata$Age[metadata$Patient == "BC10"] <- 82
metadata$Age[metadata$Patient == "BC11"] <- 47 
```

```{r}
metadata$Stage <- metadata$Patient
metadata$Stage[metadata$Patient == "BC01"] <- "IA"
metadata$Stage[metadata$Patient == "BC02"] <- "IIIA"
metadata$Stage[metadata$Patient == "BC03"] <- "IIB"
metadata$Stage[metadata$Patient == "BC04"] <- "IIA"
metadata$Stage[metadata$Patient == "BC05"] <- "IB"
metadata$Stage[metadata$Patient == "BC06"] <- "IIB"
metadata$Stage[metadata$Patient == "BC07"] <- "IIIC"
metadata$Stage[metadata$Patient == "BC08"] <- "IIA"
metadata$Stage[metadata$Patient == "BC09"] <- "IIA"
metadata$Stage[metadata$Patient == "BC10"] <- "IIIA"
metadata$Stage[metadata$Patient == "BC11"] <- "IIA"
```

```{r}
metadata$Race <- NA
metadata$Menopause <- NA
metadata$Parity <- NA
```

```{r}
metadata[1:5,]
```

```{r}
#saveRDS(metadata, "/mnt/nmorais-nfs/marta/pC_myeinfobank/metadata/chung-2017/chung-2017-clinical-metadata.rds")
```









