---
title: "Azizi 2018 metadata - indrop"
output:
  pdf_document: default
  html_notebook:
    code_folding: hide
    depth: 3
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
  word_document: default
---

```{r}
globus_metadata <- readRDS("/mnt/nmorais-nfs/marta/pC_myeinfobank/metadata/globus/processed/GSE114725_azizi_indrop.rds")
```

```{r}
globus_metadata
```

```{r}
colnames(globus_metadata)[1:5]
```

```{r}
colnames(globus_metadata@meta.data)
```
```{r}
table(globus_metadata$patient)
table(globus_metadata$batch)
table(globus_metadata$condition)
table(globus_metadata$sex)
table(globus_metadata$tissue)
```

```{r}
metadata <- data.frame(Cell_ID = colnames(globus_metadata),
                       Sample = globus_metadata$patient)
rownames(metadata) <- NULL
```

```{r}
metadata$Sample_Type <- "Fresh"
metadata$Protocol <- "inDrop_v2"
metadata$Technology <- "inDrop"
metadata$Dissociation <- "Mechanical,Enzymatic"
metadata$CellOrNucleus <- "Cell"
metadata$Sequencing_Machine <- "Illumina_HiSeq_2500"
metadata$Preprocessing <- "SEQC"
metadata$Reference_Genome <- "GRCh38"
metadata$Gender <- "Female"
metadata$Race <- NA
metadata$Parity <- NA
metadata$Treatment_Status <- NA
metadata$Treatment_Type <- NA
metadata$Stage <- NA
```

```{r}
metadata$Patient <- metadata$Sample
metadata$Patient <- gsub("_[1-8]$","", metadata$Patient)
table(metadata$Patient, metadata$Sample)
```

```{r}
metadata$Age <- metadata$Patient
metadata$Age[metadata$Age == "BC1"] <- 38
metadata$Age[metadata$Age == "BC2"] <- 60
metadata$Age[metadata$Age == "BC3"] <- 43
metadata$Age[metadata$Age == "BC4"] <- 52
metadata$Age[metadata$Age == "BC5"] <- 78
metadata$Age[metadata$Age == "BC6"] <- 58
metadata$Age[metadata$Age == "BC7"] <- 65
metadata$Age[metadata$Age == "BC8"] <- 72
```

```{r}
metadata$Subtype <- metadata$Patient
metadata$Subtype[metadata$Subtype == "BC1"] <- "ER+/PR+"
metadata$Subtype[metadata$Subtype == "BC2"] <- "ER+"
metadata$Subtype[metadata$Subtype == "BC3"] <- "TNBC"
metadata$Subtype[metadata$Subtype == "BC4"] <- "ER+/PR+"
metadata$Subtype[metadata$Subtype == "BC5"] <- "TNBC"
metadata$Subtype[metadata$Subtype == "BC6"] <- "ER+"
metadata$Subtype[metadata$Subtype == "BC7"] <- "HER2+"
metadata$Subtype[metadata$Subtype == "BC8"] <- "TNBC"
```

```{r}
metadata$Cancer_Type <- metadata$Patient
metadata$Cancer_Type[metadata$Cancer_Type == "BC1"] <- "IDC"
metadata$Cancer_Type[metadata$Cancer_Type == "BC2"] <- "IDC"
metadata$Cancer_Type[metadata$Cancer_Type == "BC3"] <- "IDC"
metadata$Cancer_Type[metadata$Cancer_Type == "BC4"] <- "IDC"
metadata$Cancer_Type[metadata$Cancer_Type == "BC5"] <- "IDC"
metadata$Cancer_Type[metadata$Cancer_Type == "BC6"] <- "IDC"
metadata$Cancer_Type[metadata$Cancer_Type == "BC7"] <- "IDC"
metadata$Cancer_Type[metadata$Cancer_Type == "BC8"] <- "IDC"
```

```{r}
metadata$Grade <- metadata$Patient
metadata$Grade[metadata$Grade == "BC1"] <- 1
metadata$Grade[metadata$Grade == "BC2"] <- 2
metadata$Grade[metadata$Grade == "BC3"] <- 3
metadata$Grade[metadata$Grade == "BC4"] <- 1
metadata$Grade[metadata$Grade == "BC5"] <- 3
metadata$Grade[metadata$Grade == "BC6"] <- 2
metadata$Grade[metadata$Grade == "BC7"] <- 3
metadata$Grade[metadata$Grade == "BC8"] <- 2
```

```{r}
metadata$Menopause <- metadata$Patient
metadata$Menopause[metadata$Menopause == "BC1"] <- "Pre"
metadata$Menopause[metadata$Menopause == "BC2"] <- "Post"
metadata$Menopause[metadata$Menopause == "BC3"] <- "Pre"
metadata$Menopause[metadata$Menopause == "BC4"] <- "Pre"
metadata$Menopause[metadata$Menopause == "BC5"] <- "Post"
metadata$Menopause[metadata$Menopause == "BC6"] <- "Post"
metadata$Menopause[metadata$Menopause == "BC7"] <- "Post"
metadata$Menopause[metadata$Menopause == "BC8"] <- "Post"
```

```{r}
metadata$Tissue <- "Tumour"
```

```{r}
metadata[1:5,]
```

```{r}
#saveRDS(metadata, "azizi-2018-indrop-clinical-metadata.rds")
```





