---
title: "bassez-2021 metadata"
output:
  pdf_document: default
  html_notebook:
    code_folding: hide
    depth: 3
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
  word_document: default
---

```{r}
globus_metadata <- read.table("/mnt/nmorais-nfs/marta/pC_myeinfobank/metadata/globus/bassez_metadata.txt")
```

```{r}
globus_barcodes <- read.table("/mnt/nmorais-nfs/marta/pC_myeinfobank/metadata/globus/bassez_barcodes.txt")
```

```{r}
globus_metadata[1:5,]
```

```{r}
globus_barcodes[1:5,]
```

```{r}
metadata <- data.frame(Cell_ID = globus_metadata$V4[-1],
                       Treatment_Status = globus_metadata$V7[-1],
                       Subtype = globus_metadata$V11[-1],
                       Patient = globus_metadata$V13[-1]
                       )
```

```{r}
cohort1 <- read.table("1872-BIOKEY_metaData_cohort1_web.csv", sep = ",")
cohort2 <- read.table("1871-BIOKEY_metaData_cohort2_web.csv", sep = ",")
```

```{r}
cohort1[1:5,]
```

```{r}
cohort2[1:5,]
```


```{r}
table(metadata$Treatment_Status)
metadata$Treatment_Status[metadata$Treatment_Status == "treatment_naive"] <- "Naive"
metadata$Treatment_Status[metadata$Treatment_Status == "neoadjuvant_chemo"] <- "Treated"
table(metadata$Treatment_Status)
```

```{r}
table(metadata$Subtype)
table(cohort1$V7)
table(cohort2$V7)

subtypes <- c(cohort1$V7[-1], cohort2$V7[-1])
table(subtypes)

barcodes <- c(cohort1$V1[-1], cohort2$V1[-1])
barcodes[1:5]

subtypes <- subtypes[order(barcodes)]
barcodes <- barcodes[order(barcodes)]
barcodes[1:5]

metadata <- metadata[order(metadata$Cell_ID),]

subtypes <- subtypes[barcodes %in% metadata$Cell_ID]
barcodes <- barcodes[barcodes %in% metadata$Cell_ID]

identical(barcodes,metadata$Cell_ID)

metadata$Subtype <- subtypes
table(metadata$Subtype)
```

```{r}
table(metadata$Patient, metadata$Subtype)
table(cohort1$V4[-1], cohort1$V7[-1])
```

```{r}
metadata$Dissociation <- "Mechanical,Enzymatic"
metadata$Protocol <- "10X_chromium_5'"
metadata$Technology <- "10X_Genomics"
metadata$Sample_Type <- "Fresh"
metadata$CellOrNucleus <- "Cell"
metadata$Sequencing_Machine <- "Illumina_NextSeq/NovaSeq6000"
metadata$Preprocessing <- "CellRanger"
metadata$Reference_Genome <- "GRCh38"
```

```{r}
metadata$Treatment_Type <- metadata$Treatment_Status
metadata$Treatment_Type[metadata$Treatment_Status == "Treated"] <- "Pembrolizumab"
metadata$Treatment_Type[metadata$Treatment_Status == "Naive"] <- "None"
metadata$Treatment_Type[metadata$Treatment_Status == "Treated" & 
                       metadata$Subtype == "HER2+" ] <- "Pembrolizumab, anti-HER2"
table(metadata$Treatment_Type, metadata$Treatment_Status)
table(metadata$Treatment_Type, metadata$Subtype)
```

```{r}
rownames(metadata) <- NULL
```


```{r}
metadata$Age_Category <- metadata$Patient
metadata$Age_Category[metadata$Patient == "BIOKEY_1"] <- "30-40"
metadata$Age_Category[metadata$Patient == "BIOKEY_10"] <- "41-50"
metadata$Age_Category[metadata$Patient == "BIOKEY_11"] <- "51-60"
metadata$Age_Category[metadata$Patient == "BIOKEY_12"] <- "61-70"
metadata$Age_Category[metadata$Patient == "BIOKEY_13"] <- "41-50"
metadata$Age_Category[metadata$Patient == "BIOKEY_14"] <- "81-90"
metadata$Age_Category[metadata$Patient == "BIOKEY_15"] <- "41-50"
metadata$Age_Category[metadata$Patient == "BIOKEY_16"] <- "51-60"
metadata$Age_Category[metadata$Patient == "BIOKEY_17"] <- "41-50"
metadata$Age_Category[metadata$Patient == "BIOKEY_18"] <- "71-80"
metadata$Age_Category[metadata$Patient == "BIOKEY_19"] <- "61-70"
metadata$Age_Category[metadata$Patient == "BIOKEY_2"] <- "71-80"
metadata$Age_Category[metadata$Patient == "BIOKEY_20"] <- "51-60"
metadata$Age_Category[metadata$Patient == "BIOKEY_21"] <- "41-50"
metadata$Age_Category[metadata$Patient == "BIOKEY_22"] <- "51-60"
metadata$Age_Category[metadata$Patient == "BIOKEY_23"] <- "71-80"
metadata$Age_Category[metadata$Patient == "BIOKEY_24"] <- "41-50"
metadata$Age_Category[metadata$Patient == "BIOKEY_25"] <- "61-70"
metadata$Age_Category[metadata$Patient == "BIOKEY_26"] <- "71-80"
metadata$Age_Category[metadata$Patient == "BIOKEY_27"] <- "61-70"
metadata$Age_Category[metadata$Patient == "BIOKEY_28"] <- "61-70"
metadata$Age_Category[metadata$Patient == "BIOKEY_29"] <- "51-60"
metadata$Age_Category[metadata$Patient == "BIOKEY_3"] <- "41-50"
metadata$Age_Category[metadata$Patient == "BIOKEY_30"] <- "41-50"
metadata$Age_Category[metadata$Patient == "BIOKEY_31"] <- "61-70"
metadata$Age_Category[metadata$Patient == "BIOKEY_32"] <- "61-70"
metadata$Age_Category[metadata$Patient == "BIOKEY_33"] <- "30-40"
metadata$Age_Category[metadata$Patient == "BIOKEY_34"] <- "51-60"
metadata$Age_Category[metadata$Patient == "BIOKEY_35"] <- "30-40"
metadata$Age_Category[metadata$Patient == "BIOKEY_36"] <- "71-80"
metadata$Age_Category[metadata$Patient == "BIOKEY_37"] <- "51-60"
metadata$Age_Category[metadata$Patient == "BIOKEY_38"] <- "51-60"
metadata$Age_Category[metadata$Patient == "BIOKEY_39"] <- "30-40"
metadata$Age_Category[metadata$Patient == "BIOKEY_4"] <- "41-50"
metadata$Age_Category[metadata$Patient == "BIOKEY_40"] <- "51-60"
metadata$Age_Category[metadata$Patient == "BIOKEY_41"] <- "41-50"
metadata$Age_Category[metadata$Patient == "BIOKEY_42"] <- "61-70"
metadata$Age_Category[metadata$Patient == "BIOKEY_5"] <- "61-70"
metadata$Age_Category[metadata$Patient == "BIOKEY_6"] <- "51-60"
metadata$Age_Category[metadata$Patient == "BIOKEY_7"] <- "41-50"
metadata$Age_Category[metadata$Patient == "BIOKEY_8"] <- "71-80"
metadata$Age_Category[metadata$Patient == "BIOKEY_9"] <- "41-50"
```

```{r}
table(metadata$Age_Category, metadata$Patient)
```

```{r}
metadata$Menopause <- metadata$Patient
metadata$Menopause[metadata$Patient == "BIOKEY_1"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_10"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_11"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_12"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_13"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_14"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_15"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_16"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_17"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_18"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_19"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_2"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_20"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_21"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_22"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_23"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_24"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_25"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_26"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_27"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_28"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_29"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_3"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_30"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_31"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_32"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_33"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_34"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_35"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_36"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_37"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_38"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_39"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_4"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_40"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_41"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_42"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_5"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_6"] <- "Post"
metadata$Menopause[metadata$Patient == "BIOKEY_7"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_8"] <- "Pre"
metadata$Menopause[metadata$Patient == "BIOKEY_9"] <- "Post"

```

```{r}
metadata$Cancer_Type <- metadata$Patient
metadata$Cancer_Type[metadata$Patient == "BIOKEY_1"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_10"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_11"] <- "ST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_12"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_13"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_14"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_15"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_16"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_17"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_18"] <- "ST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_19"] <- "ST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_2"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_20"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_21"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_22"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_23"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_24"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_25"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_26"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_27"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_28"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_29"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_3"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_30"] <- "ST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_31"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_32"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_33"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_34"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_35"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_36"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_37"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_38"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_39"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_4"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_40"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_41"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_42"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_5"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_6"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_7"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_8"] <- "IBC-NST"
metadata$Cancer_Type[metadata$Patient == "BIOKEY_9"] <- "IBC-NST"

```


```{r}
table(metadata$Menopause, metadata$Patient)
```

```{r}
metadata$Grade <- metadata$Patient
metadata$Grade[metadata$Patient == "BIOKEY_1"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_10"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_11"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_12"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_13"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_14"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_15"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_16"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_17"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_18"] <- "2"
metadata$Grade[metadata$Patient == "BIOKEY_19"] <- "2"
metadata$Grade[metadata$Patient == "BIOKEY_2"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_20"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_21"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_22"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_23"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_24"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_25"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_26"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_27"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_28"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_29"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_3"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_30"] <- "2"
metadata$Grade[metadata$Patient == "BIOKEY_31"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_32"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_33"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_34"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_35"] <- "2"
metadata$Grade[metadata$Patient == "BIOKEY_36"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_37"] <- "1"
metadata$Grade[metadata$Patient == "BIOKEY_38"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_39"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_4"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_40"] <- "2"
metadata$Grade[metadata$Patient == "BIOKEY_41"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_42"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_5"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_6"] <- "2"
metadata$Grade[metadata$Patient == "BIOKEY_7"] <- "3"
metadata$Grade[metadata$Patient == "BIOKEY_8"] <- "1"
metadata$Grade[metadata$Patient == "BIOKEY_9"] <- "3"
```

```{r}
metadata$Primary_Tumour <- metadata$Patient
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_1"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_10"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_11"] <- "pT1"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_12"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_13"] <- "pT1"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_14"] <- "pT1"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_15"] <- "pT1"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_16"] <- "pT3"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_17"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_18"] <- "pT3"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_19"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_2"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_20"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_21"] <- "pT3"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_22"] <- "pT1"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_23"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_24"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_25"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_26"] <- "pT3"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_27"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_28"] <- "pT3"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_29"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_3"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_30"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_31"] <- "pT1"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_32"] <- "ypT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_33"] <- "ypT1"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_34"] <- "ypT1"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_35"] <- "ypT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_36"] <- "ypT1"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_37"] <- "ypT3"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_38"] <- "ypT0"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_39"] <- "ypT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_4"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_40"] <- "ypT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_41"] <- "ypT1"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_42"] <- "ypT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_5"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_6"] <- "pT3"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_7"] <- "pT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_8"] <- "rpT2"
metadata$Primary_Tumour[metadata$Patient == "BIOKEY_9"] <- "pT1"
```

```{r}
metadata$Nodes <- metadata$Patient
metadata$Nodes[metadata$Patient == "BIOKEY_1"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_10"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_11"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_12"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_13"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_14"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_15"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_16"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_17"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_18"] <- "pN3"
metadata$Nodes[metadata$Patient == "BIOKEY_19"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_2"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_20"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_21"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_22"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_23"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_24"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_25"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_26"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_27"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_28"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_29"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_3"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_30"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_31"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_32"] <- "pN3"
metadata$Nodes[metadata$Patient == "BIOKEY_33"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_34"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_35"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_36"] <- "pN2"
metadata$Nodes[metadata$Patient == "BIOKEY_37"] <- "pN3"
metadata$Nodes[metadata$Patient == "BIOKEY_38"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_39"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_4"] <- "pN0"
metadata$Nodes[metadata$Patient == "BIOKEY_40"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_41"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_42"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_5"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_6"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_7"] <- "pN1"
metadata$Nodes[metadata$Patient == "BIOKEY_8"] <- "pNx"
metadata$Nodes[metadata$Patient == "BIOKEY_9"] <- "pN0"
```

```{r}
metadata$Gender <- NA
metadata$Age <- NA
metadata$Race <- NA
metadata$Menopause <- NA
metadata$Parity <- NA
metadata$Stage <- NA
metadata$Tissue <- "Tumour"
```

```{r}
metadata[1:5,]
```

```{r}
#saveRDS(metadata, 
#        "/mnt/nmorais-nfs/marta/pC_myeinfobank/metadata/bassez-2021/bassez-2021-clinical-metadata.rds")
```



